TaskManager.Web.MVC/Controllers/TaskController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Core;
using TaskManager.Core.Service.Interfaces;
using TaskManager.Data.Model;
using TaskManager.Web.MVC.ViewModel;

namespace TaskManager.Web.MVC.Controllers
{
    public class TaskController : Controller
    {

        private readonly ITaskService _taskService;
        private readonly IUserService _userService;
        private readonly ITaskStatusService _taskStatusService;
        private readonly ITaskListService _taskListService;
  

        public TaskController(ITaskService taskService, IUserService userService, ITaskStatusService taskStatusService, ITaskListService taskListService)
        {
            _taskService = taskService;
            _userService = userService;
            _taskStatusService = taskStatusService;
            _taskListService = taskListService;
        }

        [Authorize]
        public ActionResult Index()
        {
            ViewBag.UserID = GetUserIdentityID();
            var taskViewModel = Mapper.Map<IEnumerable<TB_Task>, IEnumerable<TaskViewModel>>(_taskService.GetAll());
            return View(taskViewModel);
        }

        [Authorize]
        public ActionResult Details(int id)
        {

            var taskViewModel = Mapper.Map<TB_Task, TaskViewModel>(_taskService.GetById(id));
            return View(taskViewModel);
        }

        [Authorize]
        public ActionResult Create()
        {
            if (User.IsInRole("Master"))
                ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name");
            else
                ViewBag.UserID = GetUserIdentityID().ToString();
            
            ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status");

            return View();
        }

        // POST: Task/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(TaskViewModel task)
        {

            if (!User.IsInRole("Master"))
            {
                task.UserID = GetUserIdentityID();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    //valida se usuário possui outras tarefas em produção.
                    bool userTasksInProduction = this.validateUserTasksInProduction(task.UserID, (Enums.EnumTaskStatus)task.StatusID);

                    if (userTasksInProduction)
                    {
                        ModelState.AddModelError("", "Cada usuário só pode ter uma tarefa [Em produção] por vez.");
                    }
                    //validação para UserID não consta na ViewModel.
                    else if (!task.UserID.HasValue)
                    {
                        ModelState.AddModelError("UserID", "Preencha o campo usuário.");
                    }
                    else
                    {
                        var newTask = Mapper.Map<TaskViewModel, TB_Task>(task);
                        _taskService.Add(newTask);

                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Erro ao criar tarefa. ERRO: "+ ex.Message);
            }

          
            if (User.IsInRole("Master"))
                ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name", task.UserID);
            else
                ViewBag.UserID = GetUserIdentityID().ToString();

            ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status", task.StatusID);

            return View(task);
        }

       
        [Authorize]
        public ActionResult Edit(int id)
        {
            
            var task = _taskService.GetById(id);
            var taskViewModel = Mapper.Map<TB_Task, TaskViewModel>(task);

            ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name",task.userID);
            ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status",task.statusID);

            return View(taskViewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskViewModel task)
        {
            try
            {

                if (!User.IsInRole("Master"))
                {
                    task.UserID = GetUserIdentityID();
                }

                if (ModelState.IsValid)
                {

                    var editTask = _taskService.GetById(task.ID);

                    //tarefa finalizada não pode ser alterada.
                    if ((Enums.EnumTaskStatus)editTask.statusID == Enums.EnumTaskStatus.Finalizada)
                    {

                        //throw new Exception("Uma vez [Finalizada] a tarefa completou o fluxo e nenhuma informação pode ser alterada.");
                        ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name", task.UserID);
                        ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status", task.StatusID);

                        ModelState.AddModelError("", "Uma vez [Finalizada] a tarefa completou o fluxo e nenhuma informação pode ser alterada.");
                        return View(task);
                    }

                        //valida se usuário possui outras tarefas em produção.
                    bool userTasksInProduction = this.validateUserTasksInProduction(task.UserID, (Enums.EnumTaskStatus)task.StatusID);

                    if (userTasksInProduction)
                    {
                        ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name", task.UserID);
                        ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status", task.StatusID);

                        ModelState.AddModelError("", "Cada usuário só pode ter uma tarefa [Em produção] por vez.");
                        return View(task);
                    }

                    //valida se possui tarefas dependentes finalizadas para ir para produção
                    if ((Enums.EnumTaskStatus)task.StatusID == Enums.EnumTaskStatus.Emproducao)
                    {
                        IEnumerable<TB_TaskList> taskList = _taskService.GetDepedencyTaskList(editTask);
                        if (taskList.Any())
                        {
                            ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name", task.UserID);
                            ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status", task.StatusID);

                            ModelState.AddModelError("", "Tarefas com dependências, precisam que as mesmas tenham sido [finalizadas] para poder iniciar [em produção].");
                            return View(task);
                        }
                    }

                    if (!_taskService.validateStatusUpdate((Enums.EnumTaskStatus)editTask.statusID, (Enums.EnumTaskStatus)task.StatusID))
                    {

                        ModelState.AddModelError("", "Mudança de status não permitida: " + 
                                                    Enums.GetDescription((Enums.EnumTaskStatus)editTask.statusID) + " para " +
                                                    Enums.GetDescription((Enums.EnumTaskStatus)task.StatusID)) ;
                    
                    }
                    else
                    {
                        
                        editTask.statusID = task.StatusID;
                        editTask.userID = task.UserID;

                        _taskService.Update(editTask);
                        return RedirectToAction("Index");

                    }

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Erro ao alterar tarefa.  ERRO: " + ex.Message);
            }
            
            ViewBag.UserID = new SelectList(_userService.GetAll(), "ID", "Name", task.UserID);
            ViewBag.StatusID = new SelectList(_taskStatusService.GetAll(), "ID", "Status", task.StatusID);
            
            return View(task);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var task = _taskService.GetById(id);
            var taskViewModel = Mapper.Map<TB_Task, TaskViewModel>(task);

            return View(taskViewModel);
        }

        // POST: Task/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Delete(TaskViewModel task)
        {
            try
            {
                
                var deleteTask = _taskService.GetById(task.ID);
            
                bool checkDepAndReq = _taskListService.checkDependencyAndRequiriment(task.ID);

                if (checkDepAndReq)
                {
                    task = Mapper.Map<TB_Task , TaskViewModel>(deleteTask);
                    ModelState.AddModelError("", "Exclusão não permitida. Existem tarefas pendentes e|ou pré-requisitos para essa tarefa ou a mesma está associada a outras tarefas.");
                }
                else
                {
                    _taskService.Remove(deleteTask);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Erro ao deletar task. ERRO: " + ex.Message);
            }
            return View(task);
        }


        private int GetUserIdentityID()
        {
            var user = _userService.GetUserByEmail(User.Identity.Name);

            return user.ID; 
        }
        /// <summary>
        /// Valida se existem tarefas em produção para o usuário ao alterar tarefa para produção.
        /// </summary>
        /// <param name="userID">usuário</param>

TaskManager.Web.MVC/Controllers/TaskListController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Core.Service.Interfaces;
using TaskManager.Data.Model;
using TaskManager.Web.MVC.ViewModel;

namespace TaskManager.Web.MVC.Controllers
{
    public class TaskListController : Controller
    {
        private readonly ITaskListService _taskListService;
        private readonly ITaskService _taskService;

        public TaskListController(ITaskListService taskListService, ITaskService taskService)
        {
            _taskListService = taskListService;
            _taskService = taskService;
        }

        // GET: TaskList
        [Authorize]
        public ActionResult Index(int id)
        {
            ViewBag.id = id;
            var taskListViewModel = Mapper.Map<IEnumerable<TB_TaskList>, IEnumerable<TaskListViewModel>>(_taskListService.GetByMainTaskID(id));
            return View(taskListViewModel);
        }

        // GET: TaskList/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TaskList/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            ViewBag.taskID = new SelectList(_taskService.GetAll().Where(t => t.ID != id) , "ID", "description");
            ViewBag.id = id;
            return View();
        }

        // POST: TaskList/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskListViewModel taskList)
        {
            taskList.mainTaskID = taskList.ID;

            try
            {
                if (ModelState.IsValid)
                {

                    if (taskList.dependency == taskList.requeriment)
                    {
                        ModelState.AddModelError("", "Favor selecionar dependência OU pré-requisito. ");
                    }
                    else
                    {
                        var newTaskList = Mapper.Map<TaskListViewModel, TB_TaskList>(taskList);
                        _taskListService.Add(newTaskList);

                        return RedirectToAction("Index", new { id = taskList.mainTaskID });
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Erro ao cadastrar usuário. ERRO: " + ex.Message);
            }

            ViewBag.taskID = new SelectList(_taskService.GetAll(), "ID", "description", taskList.taskID);
            ViewBag.mainTaskID = taskList.mainTaskID;
            return View(taskList);
        }

        // GET: TaskList/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TaskList/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TaskList/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {

             var task = _taskListService.GetByTaskListID(id);
             var taskListViewModel = Mapper.Map<TB_TaskList, TaskListViewModel>(task);
             ViewBag.mainTaskID = task.mainTaskID;
           
            return View(taskListViewModel);
        }

        // POST: TaskList/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(TaskListViewModel taskList)
        {
            try
            {
                var deleteTask = _taskListService.GetById(taskList.ID);
                ViewBag.mainTaskID = deleteTask.mainTaskID;

                Mapper.Map(taskList, deleteTask);
                _taskListService.Remove(deleteTask);

                return RedirectToAction("Index", new { id = ViewBag.mainTaskID } );
                //TempData["success"] = "Tarefa desassociada com sucesso.";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("","Erro ao deletar usuário. ERRO: " + ex.Message);    
            }
            return View(taskList);
        }
    }
}

TaskManager.Web.MVC/Views/TaskList/Create.cshtml
@model TaskManager.Web.MVC.ViewModel.TaskListViewModel


@{
    ViewBag.Title = "Create";
}

<h2>Cadastro</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class="form-group">
            @Html.LabelFor(model => model.mainTaskID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mainTaskID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mainTaskID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.taskID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.taskID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.taskID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TB_Task, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("taskID", "Tarefa")
                @Html.ValidationMessageFor(model => model.taskID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.requeriment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.requeriment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.requeriment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dependency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.dependency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dependency, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<<Voltar", "Index", new { id = ViewBag.id })
</div>

TaskManager.Web.MVC/Views/TaskList/Delete.cshtml
@model TaskManager.Web.MVC.ViewModel.TaskListViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<div>
    <h4>Tarefas pré-requisitos e dependentes.</h4>
    <hr />


    @if (TempData["success"] != null) { 
    <div>
        @Html.Encode(TempData["success"])
     </div>
     }

            <dl class="dl-horizontal">
                <dt>
                    Tarefa Principal
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TB_Task.description)
                </dd>
            
    <hr />
                 <dt>
                    Tarefa associada
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TB_Task1.description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.requeriment)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.requeriment)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.dependency)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.dependency)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("<< Voltar", "Index", new { id = ViewBag.mainTaskID })
                </div>
            }
        </div>

TaskManager.Web.MVC/Views/TaskList/Index.cshtml
@model IEnumerable<TaskManager.Web.MVC.ViewModel.TaskListViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Tarefas pré-requisitos e dependentes</h2>

<p>
    @Html.ActionLink("Criar nova", "Create", new { id = ViewBag.id })
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.TB_Task1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TB_Task1.TB_TaskStatus.status)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.taskID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.requeriment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dependency)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(model => item.TB_Task1.description)
        </td>
        <td>
            @Html.DisplayFor(model => item.TB_Task1.TB_TaskStatus.status)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.taskID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.requeriment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dependency)
        </td>
        <td>
            @Html.ActionLink("Deletar", "Delete", new { id = item.ID })
        </td>
    </tr>
}
   
</table>

<div>
    @Html.ActionLink("<< Voltar", "Index", "Task")
</div>